version: '3'
volumes:
  mysql_data:
    driver:local
services:
  mysql:
    image: 'bitnami/mariadb:latest'
    volumes:
      - ./data/mysql/script:/usr/mysql/script
      - mysql_data:/var/lib/mysql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
  app:
    
